version: '3'
services:
  postgres:
    image: postgres
    container_name: database-container
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
